// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WowCharComparerWebApp.Data.Database;

namespace WowCharComparerWebApp.Migrations
{
    [DbContext(typeof(ComparerDatabaseContext))]
    [Migration("20190711181707_user-pass-encryption-2")]
    partial class userpassencryption2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WowCharComparerWebApp.Models.Achievement.AchievementCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("AchievementCategory");
                });

            modelBuilder.Entity("WowCharComparerWebApp.Models.Achievement.AchievementsData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AchievementCategoryID");

                    b.Property<string>("Description");

                    b.Property<int>("FactionId");

                    b.Property<string>("Icon");

                    b.Property<int>("Points");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("AchievementCategoryID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("AchievementsData");
                });

            modelBuilder.Entity("WowCharComparerWebApp.Models.BonusStats", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BonusStatsID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("BonusStatsID")
                        .IsUnique();

                    b.ToTable("BonusStats");
                });

            modelBuilder.Entity("WowCharComparerWebApp.Models.Internal.APIClient", b =>
                {
                    b.Property<string>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientName")
                        .IsRequired();

                    b.Property<string>("ClientSecret")
                        .IsRequired();

                    b.Property<DateTime>("ValidationUntil");

                    b.HasKey("ClientID");

                    b.ToTable("APIClient");
                });

            modelBuilder.Entity("WowCharComparerWebApp.Models.Internal.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<bool>("IsOnline");

                    b.Property<DateTime>("LastLoginDate");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("PasswordRecoveryExpirationTime");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<Guid>("VerificationToken");

                    b.Property<bool>("Verified");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WowCharComparerWebApp.Models.Achievement.AchievementsData", b =>
                {
                    b.HasOne("WowCharComparerWebApp.Models.Achievement.AchievementCategory")
                        .WithMany("AchievementsData")
                        .HasForeignKey("AchievementCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
